version: "3"
services:
  trade-service:
    image: ericccw/fx-trade-service:1.0.0
    ports:
      - 8090:8090
    environment:
      - APP_TRADE_MAX=500
      - APP_POLLSIZE_MAX=5
    networks:
      - network
  backoffice:
    image: ericccw/fx-backoffice:1.0.0
    ports:
      - 8443:8443
    depends_on:
      - trade-service
    networks:
      - network

networks:
  network:
